[features]
seeds = false
[programs.localnet]
proposal_voting = "84FV6Zmu8WLxmUqY5GFKKkkmbzm9CrpfEkf63qTQtdCE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/billlu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
